version: "3.1"
services:
  web:
    container_name: 1of2_api
    build: .
    env_file:
      - .env
    links:
      - db
      - redis
    ports:
      - ${WEB_PORT:-42123}:42123 # Application port
      - ${WEB_DEBUG_PORT:-9222}:9222 # Debugging port
    environment:
      REDISCLOUD_URL: redis://1of2_cache
      DATABASE_URL: postgres://1of2@db:5432/1of2

    volumes:
      - .:/usr/src/app
      # More info on the node_modules volume at:
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      # under "The node_modules Volume Trick"
      - /usr/src/app/node_modules
    # Run nodemon with legacy watch
    # https://github.com/remy/nodemon#application-isnt-restarting
    # Ignore public/ because generating documentation programatically
    # on startup was causing an infinite loop
    command: yarn debug
    depends_on:
      - db
      - redis

  # Should only be used in development, we use seperate host for staging and prod
  db:
    image: postgres:latest
    container_name: 1of2_db
    command: ["postgres", "-c", "max_connections=200"]
    restart: always
    networks:
      - default
    ports:
      - ${PG_DATABASE_PORT:-5432}:5432
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/1-database.sql
      - postgres-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "1of2"
      POSTGRES_DB: "1of2"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis
    container_name: 1of2_cache
    ports:
      # expose for local testing
      - ${API_REDIS_PORT:-6379}:6379

volumes:
  # Database named module has to be declared globally
  postgres-storage:
